// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { WebViewStorage } from '@/lib/webview-storage';

const SUPABASE_URL = "https://dbptgehpknjsoisirviz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRicHRnZWhwa25qc29pc2lydml6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NjIxNDUsImV4cCI6MjA3MDIzODE0NX0.D1uw0ui_auBAi-dvodv6j2a9x3lvMnY69cDa9Wupjcs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Detect if running in WebView
const isWebView = /wv|WebView/i.test(navigator.userAgent);

// Use custom storage for WebView, fallback to localStorage
const storage = isWebView ? new WebViewStorage() : localStorage;

console.log(`🔧 Supabase client initialized with ${isWebView ? 'WebViewStorage' : 'localStorage'}`);

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: storage as any,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  }
});